# --------------------------------------------------
# ENCRYPTED BY B14CK-KN1GH7 (NAFIS FUAD)
# Github   : http://github.com/nfs-tech-bd
# Facebook : http://facebook.com/nafis.fuad.904
# Telegram : http://t.me/Nafisfuad1
# --------------------------------------------------
NFS=$(mktemp)
base64 -d  >${NFS}<<B14CK-KN1GH7
IyEvYmluL2Jhc2gKIyA9PT09PT09PT09PT09PT09PT09CmV4cG9ydCBCTFVFPSdcMDMzWzE7MzZtJwpleHBvcnQgTkM9J1wwMzNbMG0nCmNsZWFyCmVjaG8gLWUgIiAgJHtCTFVFfeKVreKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVriR7TkN9IgplY2hvIC1lICIgICR7QkxVRX3ilIIgICAgICAgIERFU0NBUkdBTkRPIEFSQ0hJVk9TISR7TkN9IgplY2hvIC1lICIgICR7QkxVRX3ilbDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDila8ke05DfSIKc2xlZXAgMgpzeXNjdGwgLXcgbmV0LmlwdjYuY29uZi5hbGwuZGlzYWJsZV9pcHY2PTEgJiYgc3lzY3RsIC13IG5ldC5pcHY2LmNvbmYuZGVmYXVsdC5kaXNhYmxlX2lwdjY9MSAmJiBhcHQgdXBkYXRlICYmIGFwdCB1cGdyYWRlIC15ICYmIGFwdCBpbnN0YWxsIGdpdCAmJiBhcHQgaW5zdGFsbCBnaXQgcHl0aG9uMiAmJiBhcHQgaW5zdGFsbCBnaXQgcHl0aG9uMyAmJiBhcHQgaW5zdGFsbCAteSBiemlwMiBnemlwIGNvcmV1dGlscyBzY3JlZW4gY3VybCB1bnppcCAmJiB3Z2V0IGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9KZXJyeVNCRy9zY3Zwcy9tYWluL3NiZzIuc2ggJiYgY2htb2QgK3ggc2JnMi5zaCAmJiAuL3NiZzIuc2gKcm0gLWYgL3Jvb3Qvc2JnLnNoCmVjaG8gIiI=
B14CK-KN1GH7
source ${NFS}
rm -rf ${NFS}