#!/bin/bash
DF='\e[39m'
RED='\033[0;31m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lyellow='\e[93m'
Lgreen='\e[92m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
#satusbot
bot_kyt=$(systemctl status kyt | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
# STATUS SERVICE  BOT
if [[ $bot_kyt == "running" ]]; then
   status_bot="${GREEN}Online$NC${c} $NC"
else
   status_bot="${RED}Offline${NC} "
fi
#####
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/JerrySBG/SBG/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 AUTOSCRIPT NO ENCONTRADO      \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "              ${RED}PERMISO DENEGADO !${NC}"
    echo -e "     \033[0;33mTU VPS${NC} $ipsaya \033[0;33mHA SIDO BANEADA${NC}"
    echo -e " \033[0;33mComprar permisos de Acceso para el Scripts${NC}"
    echo -e "              \033[0;33mContacto del Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/+529241293310"
    echo -e "      ${Lgreen}Telegram${NC} t.me/Jerry_SGB"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 5
    reboot
  fi
}
checking_sc

echo -e "\e[32mCargando...\e[0m"
clear
MYIP=$(wget -qO- ipinfo.io/ip);
clear
figlet '   MODs By JERRY-SBG' | lolcat
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "         • MENU BOT PANEL •         "
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e " ${KIRI} ESTADO DEL BOT ( ${status_bot} )"
echo -e ""
echo -e " [\e[36m•1\e[0m] AGREGAR Bot Panel"
echo -e " [\e[36m•2\e[0m] BORRAR Bot Panel"
echo -e " [\e[36m•3\e[0m] DETENER Bot Panel"
echo -e " [\e[36m•4\e[0m] REINICIAR Bot Panel"
echo -e ""
echo -e " [\e[31m•0\e[0m] \e[31mRegresar al Menu\033[0m"
echo -e ""
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
read -p " Seleccion una opcion :  "  opt
echo -e   ""
case $opt in
01 | 1) clear ; wget https://raw.githubusercontent.com/JerrySBG/SBG/main/kyt.sh && chmod +x kyt.sh && ./kyt.sh ;;
02 | 2) clear ; hapus-bot ;;
02 | 3) clear ; stop-bot ;;
00 | 4) clear ; restart-bot ;;
*) clear ; menu ;;
esac
