#!/bin/bash
MYIP=$(wget -qO- ipinfo.io/ip);
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
function notif_clearcache() {
    green "Notif AddHost BOT"
    sleep 2
    CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>◇━━━━━━━━━━━━━━◇</code>
<b>  ⚠️LIMPIEZA DE CACHE VPS⚠️</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<code>Limpieza de Cache Exitosa</code>
<code>◇━━━━━━━━━━━━━━◇</code>
<code>Telegram : @Jerry_SBG</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
echo "Comprobando VPS"
clear
echo ""
echo ""
echo -e "[ \033[32mInfo\033[0m ] Borrar caché de RAM"
echo 1 > /proc/sys/vm/drop_caches
sleep 3
echo -e "[ \033[32mok\033[0m ] Caché Borrado"
notif_clearcache
echo ""
echo -e " ${GREEN} Volver al menú en 2 segundos ${NC}"
sleep 1
menu
