#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# Getting
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/JerrySBG/SBG/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 AUTOSCRIPT NO ENCONTRADO      \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "              ${RED}PERMISO DENEGADO !${NC}"
    echo -e "     \033[0;33mTU VPS${NC} $ipsaya \033[0;33mHA SIDO BANEADA${NC}"
    echo -e " \033[0;33mComprar permisos de Acceso para el Scripts${NC}"
    echo -e "              \033[0;33mContacto del Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/+529241293310"
    echo -e "      ${Lgreen}Telegram${NC} t.me/Jerry_SGB"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 5
    reboot
  fi
}
checking_sc
echo -e "\e[32mCargando...\e[0m"
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "                 MENU VLESS              $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${ORANGE}1.${NC} \033[0;36m Crear Cuenta XRAY Vless WS/GRPC${NC}"
echo -e "  ${ORANGE}2.${NC} \033[0;36m Crear Cuenta Temporal XRAY Vless WS/GRPC${NC}"
echo -e "  ${ORANGE}3.${NC} \033[0;36m Borrar Cuenta XRAY Vless WS/GRPC${NC}"
echo -e "  ${ORANGE}4.${NC} \033[0;36m Renovar Cuenta Vless ${NC}"
echo -e "  ${ORANGE}5.${NC} \033[0;36m Comprobar Sesion de Cuenta Vless ${NC}"
echo -e "  ${ORANGE}6.${NC} \033[0;36m Comprobar Configuracion de Cuenta Vless ${NC}"
echo -e "  ${ORANGE}7.${NC} \033[0;36m Desbloquear Cuenta Vless ${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Seleccionar una de las opciones [ 1 - 6 ] : " menu
case $menu in
1)  clear ;
    addvless
    ;;
2) clear ;
    trialvless
    ;;
3) clear ;
    delvless
    ;;
4) clear ;
    renewvless
    ;;
5) clear ;
    cekvless
    ;;
6) clear ;
    user-vless
    ;;
7) clear ;
    unlock
    ;;
*)
    menu
    ;;
esac
